version: '3.8'

services:
  chat-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chat-boot-app
    ports:
      - "8080:8080"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
